spring:
  application:
    name: asp-user-service
  cloud:
    nacos:
      config:
        server-addr: 172.25.138.166:8848
        namespace: asp-service
      discovery:
        server-addr: 172.25.138.166:8848
        namespace: asp-service
        group: 1.0
        heart-beat-interval: 5
        ip-delete-timeout: 20